---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: build
    schedule:
      interval: monthly
    labels:
      - dependencies
    groups:
      actions:
        patterns:
          - "actions/*"
